### ISSUE TITLE
Need Help with GameView

### ISSUE THREAD

**Issue by YehyunLee** [YehyunLee/PokemonGame#42]
Need Help with GameView.

@Muaj 
I setup ground work for view model. (check my new branch: yehyun-groundwork_for_choosing_pokemons_view)
we will need to add pokemon sprites and convert our old code with completely new code 
Current code is content changed code. Refer to my code in case anyone using popup method
WIll be nice if @Martin @Alex can contribute as well.

Check GameView file under view folder

**Comment by Muaj17** [comment]
Completed the task. Making the view look better would be the next steps.
